#!/usr/bin/python
# -*- coding: utf-8 -*-
# File:     conf/settings.py
# Date:     2019-03-02 13:30
# Author:   Kenson Man <kenson@kenson.idv.hk>
# Desc:     Define the models for the health project;
"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9d4+exhq7pq(*5ow9_my49g7hzr+%^*k$fuylts12k+y64xz_%'
SECURE_SSL_REDIRECT=True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['locahost:8000', 'localhost', 'health.kenson.idv.hk']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
INSTALLED_APPS += ['webframe', 'method_override', 'django_tables2', 'health']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
MIDDLEWARE += [     
    'webframe.methodoverridemiddleware.MethodOverrideMiddleware', #django 1.10 or aboves
    'webframe.NextURLMiddleware.NextURLMiddleware',               #If using the social_auth_django
    'webframe.LangMiddleware.LangMiddleware',
    'webframe.CurrentUserMiddleware.CurrentUserMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'conf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'webframe.providers.absolute_path', 'webframe.providers.fmt_injection', 'webframe.providers.template_injection'
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DBNAME', 'health'), 
        'USER': os.environ.get('DBUSER', 'health'),
        'PASSWORD': os.environ.get('DBPASS', 'healthpass'),
        'HOST': os.environ.get('DBHOST', 'dbhost'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh_hant'
LANGS=(('en', 'English'), ('zh-hant', '繁體中文'))

TIME_ZONE = 'Asia/Hong_Kong'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT= 'static'
MEDIA_URL  = '/media/'
MEDIA_ROOT = 'media'
LOGIN_URL = 'webframe:login'

# Templates
TMPL_HEADER='health/header.html'
DJANGO_TABLES2_TEMPLATE = 'django_tables2/bootstrap4.html'

# Logging
if not os.path.isdir('logs'): os.mkdir('logs')
LOGGING={
   'version': 1,
   'disable_existing_loggers': False,
   'formatters': {
     'verbose': { 'format':'[%(asctime)s] %(levelname)s [%(name)s:%(filename)s:%(lineno)s] %(message)s', 'datefmt':'%d/%b/%Y %H:%M:%S' },
     'simple':  { 'format':'%(levelname)s <%(filename)s:%(lineno)d> %(message)s' },
   },
   'handlers': {
      'console': { 'level': 'DEBUG', 'class': 'logging.StreamHandler', 'formatter': 'simple' },
      'file': {'level': 'INFO', 'class': 'logging.handlers.TimedRotatingFileHandler', 'formatter': 'verbose', 'filename': './logs/runtime.log', 'when':'midnight'},
   },
   'loggers':{
     'django': {'handlers':['console', 'file'], 'propagate': True, 'level': 'WARNING'},
     'webframe': { 'handlers': ['console', ], 'level': 'WARNING'},
     'health': {'handlers': ['console', 'file'], 'level': 'DEBUG'},
   },
}

VERSION='v0.4.3'
