# Generated by Django 2.1.7 on 2019-03-02 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import webframe.CurrentUserMiddleware
import webframe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='webframe.models.ValueObject.id.helptext', primary_key=True, serialize=False, verbose_name='webframe.models.ValueObject.id')),
                ('lmd', models.DateTimeField(auto_now=True, help_text='webframe.models.ValueObject.lmd.helptext', verbose_name='webframe.models.ValueObject.lmd')),
                ('cd', models.DateTimeField(auto_now_add=True, help_text='webframe.models.ValueObject.cd.helptext', verbose_name='webframe.models.ValueObject.cd')),
                ('name', models.CharField(max_length=100, verbose_name='Category.name')),
                ('desc', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Category.desc')),
                ('minimum', models.DecimalField(decimal_places=5, default=0, max_digits=8, verbose_name='Category.minimum')),
                ('maximum', models.DecimalField(decimal_places=5, default=0, max_digits=8, verbose_name='Category.maximum')),
                ('cb', models.ForeignKey(blank=True, default=webframe.CurrentUserMiddleware.get_current_user, help_text='webframe.models.ValueObject.cb.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_cb', to=settings.AUTH_USER_MODEL, verbose_name='webframe.models.ValueObject.cb')),
                ('lmb', models.ForeignKey(blank=True, default=webframe.CurrentUserMiddleware.get_current_user, help_text='webframe.models.ValueObject.lmb.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_lmb', to=settings.AUTH_USER_MODEL, verbose_name='webframe.models.ValueObject.lmb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Category.user')),
            ],
            options={
                'verbose_name': 'webframe.models.ValueObject',
                'verbose_name_plural': 'webframe.models.ValueObjects',
                'permissions': (('view_%(class)s', 'Can view this model without ownership'),),
                'abstract': False,
            },
            bases=(models.Model, webframe.models.Dictable),
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='webframe.models.ValueObject.id.helptext', primary_key=True, serialize=False, verbose_name='webframe.models.ValueObject.id')),
                ('lmd', models.DateTimeField(auto_now=True, help_text='webframe.models.ValueObject.lmd.helptext', verbose_name='webframe.models.ValueObject.lmd')),
                ('cd', models.DateTimeField(auto_now_add=True, help_text='webframe.models.ValueObject.cd.helptext', verbose_name='webframe.models.ValueObject.cd')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Index.time')),
                ('value', models.DecimalField(decimal_places=5, default=0, max_digits=8, verbose_name='Index.value')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health.Category', verbose_name='Index.category')),
                ('cb', models.ForeignKey(blank=True, default=webframe.CurrentUserMiddleware.get_current_user, help_text='webframe.models.ValueObject.cb.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_cb', to=settings.AUTH_USER_MODEL, verbose_name='webframe.models.ValueObject.cb')),
                ('lmb', models.ForeignKey(blank=True, default=webframe.CurrentUserMiddleware.get_current_user, help_text='webframe.models.ValueObject.lmb.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_lmb', to=settings.AUTH_USER_MODEL, verbose_name='webframe.models.ValueObject.lmb')),
            ],
            options={
                'verbose_name': 'webframe.models.ValueObject',
                'verbose_name_plural': 'webframe.models.ValueObjects',
                'permissions': (('view_%(class)s', 'Can view this model without ownership'),),
                'abstract': False,
            },
            bases=(models.Model, webframe.models.Dictable),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='webframe.models.ValueObject.id.helptext', primary_key=True, serialize=False, verbose_name='webframe.models.ValueObject.id')),
                ('lmd', models.DateTimeField(auto_now=True, help_text='webframe.models.ValueObject.lmd.helptext', verbose_name='webframe.models.ValueObject.lmd')),
                ('cd', models.DateTimeField(auto_now_add=True, help_text='webframe.models.ValueObject.cd.helptext', verbose_name='webframe.models.ValueObject.cd')),
                ('name', models.CharField(max_length=100, verbose_name='Tag.name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health.Category', verbose_name='Tag.category')),
                ('cb', models.ForeignKey(blank=True, default=webframe.CurrentUserMiddleware.get_current_user, help_text='webframe.models.ValueObject.cb.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_cb', to=settings.AUTH_USER_MODEL, verbose_name='webframe.models.ValueObject.cb')),
                ('lmb', models.ForeignKey(blank=True, default=webframe.CurrentUserMiddleware.get_current_user, help_text='webframe.models.ValueObject.lmb.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_lmb', to=settings.AUTH_USER_MODEL, verbose_name='webframe.models.ValueObject.lmb')),
            ],
            options={
                'verbose_name': 'webframe.models.ValueObject',
                'verbose_name_plural': 'webframe.models.ValueObjects',
                'permissions': (('view_%(class)s', 'Can view this model without ownership'),),
                'abstract': False,
            },
            bases=(models.Model, webframe.models.Dictable),
        ),
        migrations.AddField(
            model_name='index',
            name='tags',
            field=models.ManyToManyField(to='health.Tag', verbose_name='Index.tags'),
        ),
    ]
