# Generated by Django 2.1.7 on 2019-03-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'health.models.Category', 'verbose_name_plural': 'health.models.Categories'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'health.models.Index', 'verbose_name_plural': 'health.models.Indexes'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'health.models.Tag', 'verbose_name_plural': 'health.models.Tags'},
        ),
        migrations.AddField(
            model_name='index',
            name='desc',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Index.desc'),
        ),
    ]
